//
// (c) 2019 The Super 4404 C Compiler
// A.Belin, A.Nahid, L.Ohl, L.Saos, A.Verrier, I.Zemmouri
// INSA Lyon
//

#pragma once

namespace ast
{
	// Errors generated by the AST.
	enum class Error
	{
		None,
		InvalidInstruction,
		DivisionByZero,
		NotConstant,
		NoMain,
		InvalidStatement,
		DuplicatedSymbolName,
		ExpectingExpression,
		UnknownIdentifier,
		WrongArgumentsCount,
		MissingArraySize,
		InvalidArraySize,
		MissingArrayIndex,
		IndexOutOfBounds,
		VariableDeclarationBeginningFunction
	};

	// Warnings generated by the AST.
	enum class Warning
	{
		None,
		UnusedVariable,
		UnsafeCast,
		ValueOutOfType,
		OverrideSymbolName
	};
}
